module.exports = {
  FACEBOOK_APP_ID: process.env.FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET: process.env.FACEBOOK_APP_SECRET,
  FLICKR_APP_KEY: process.env.FLICKR_APP_KEY,
  FLICKR_APP_SECRET: process.env.FLICKR_APP_SECRET,
  MEDIUM_APP_ID: process.env.MEDIUM_APP_ID,
  MEDIUM_APP_SECRET: process.env.MEDIUM_APP_SECRET,
  TWITTER_API_KEY: process.env.TWITTER_API_KEY,
  TWITTER_API_SECRET: process.env.TWITTER_API_SECRET,
};
